version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-network

  motimo:
    build:
      context: .
      dockerfile: Dockerfile-local
    container_name: motimo-local
    env_file: .env
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  my-network:
    driver: bridge
