spring:
  application:
    name: motimo-api

  datasource:
    url: jdbc:postgresql://localhost:5432/motimo?ssl=false
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: { 구글_클라이언트_ID }
            client-secret: { 구글_클라이언트_시크릿 }
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - profile
          kakao:
            client-id: { 카카오_클라이언트_ID }
            client-secret: { 카카오_클라이언트_시크릿 }
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

auth:
  jwt:
    jwt-secret:
    token-expiration:
    issuer: