spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PW}
    hikari:
      maximum-pool-size: 4
      minimum-idle: 1
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    properties:
      hibernate.transaction.jta.platform: org.hibernate.service.jta.JtaPlatform

logging:
  level:
    org.springframework.web: DEBUG
    com.fasterxml.jackson.databind: DEBUG
    com.zaxxer.hikari: DEBUG