spring:
  application:
    name: motimo-api

  datasource:
    url: jdbc:postgresql://localhost:5432/motimo?ssl=false
    username:
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
  jpa:
    database: postgresql
    show-sql: true
    #    hibernate:
    #      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
