name: Motimo Deploy with Docker

on:
  workflow_run:
    workflows: ["Motimo CI with Gradle"]
    types:
      - completed

jobs:
  docker-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Download built JAR
      uses: actions/download-artifact@v4
      with:
        name: motimo-jar
        path: motimo-api/build/libs

    - name: Extract Git short SHA
      id: git_info
      run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/motimo:${{ steps.git_info.outputs.commit_hash }} .
        docker tag ${{ secrets.DOCKER_USERNAME }}/motimo:${{ steps.git_info.outputs.commit_hash }} ${{ secrets.DOCKER_USERNAME }}/motimo:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/motimo:${{ steps.git_info.outputs.commit_hash }}
        docker push ${{ secrets.DOCKER_USERNAME }}/motimo:latest

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << EOF
          set -x
          docker pull ${{ secrets.DOCKER_USERNAME }}/motimo:${{ steps.git_info.outputs.commit_hash }}
          docker stop motimo || true
          docker rm motimo || true
          docker run -d --env-file .env \
            -e SPRING_PROFILES_ACTIVE=dv \
            --name motimo \
            -p 8080:8080 \
            ${{ secrets.DOCKER_USERNAME }}/motimo:latest
        EOF
