name: Motimo Deploy with Docker

on:
  push:
    branches: [ "main" ]

jobs:
  docker-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Extract Git short SHA
      id: git_info
      run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Build bootJar
      run: ./gradlew bootJar -x test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/motimo:${{ steps.git_info.outputs.commit_hash }} .
        docker tag ${{ secrets.DOCKER_USERNAME }}/motimo:${{ steps.git_info.outputs.commit_hash }} ${{ secrets.DOCKER_USERNAME }}/motimo:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/motimo:${{ steps.git_info.outputs.commit_hash }}
        docker push ${{ secrets.DOCKER_USERNAME }}/motimo:latest

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << EOF
          set -x
          docker pull ${{ secrets.DOCKER_USERNAME }}/motimo:${{ steps.git_info.outputs.commit_hash }}
          docker stop motimo || true
          docker rm motimo || true
          docker run --env-file .env \
            --name motimo \
            -p 8080:8080 \
            ${{ secrets.DOCKER_USERNAME }}/motimo:latest
        EOF
