name: Motimo CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.git_info.outputs.commit_hash }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Extract Git short SHA
        id: git_info
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Build JAR
        run: ./gradlew :motimo-api:bootJar -x test

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: motimo-jar
          path: motimo-api/build/libs/motimo-api-*.jar

          

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: motimo-jar
          path: motimo-api/build/libs

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Show directory contents
        run: ls -al
        working-directory: ${{ github.workspace }}

      - name: Prepare JAR for Docker
        run: |
          mkdir -p ./docker-build
          cp motimo-api/build/libs/motimo-api-*.jar ./docker-build/app.jar
        
      - name: Build and push Docker image
        run: |
          docker build -f ../Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/motimo:${{ needs.build.outputs.commit_hash }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/motimo:${{ needs.build.outputs.commit_hash }} ${{ secrets.DOCKER_USERNAME }}/motimo:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/motimo:${{ needs.build.outputs.commit_hash }}
          docker push ${{ secrets.DOCKER_USERNAME }}/motimo:latest
        working-directory: ./docker-build

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # - name: Deploy to server
      #   run: |
      #     ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << EOF
      #       set -x
      #       docker pull ${{ secrets.DOCKER_USERNAME }}/motimo:${{ needs.build.outputs.commit_hash }}
      #       docker stop motimo || true
      #       docker rm motimo || true
      #       docker run -d --env-file .env \
      #         -e SPRING_PROFILES_ACTIVE=dv \
      #         --name motimo \
      #         -p 8080:8080 \
      #         ${{ secrets.DOCKER_USERNAME }}/motimo:latest
      #     EOF

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << EOF
            set -x

            # # 이전 이미지 및 컨테이너 정리
            # docker stop motimo || true
            # docker rm motimo || true

            # # 안 쓰는 이미지 및 볼륨 정리 
            # docker image prune -f
            # docker container prune -f
            # docker volume prune -f
            
            docker ps -a --filter "ancestor=${{ secrets.DOCKER_USERNAME }}/motimo" --format "{{.ID}}" | xargs -r docker rm -f

            # motimo 컨테이너 중 이름이 있는 것도 제거
            docker stop motimo || true
            docker rm motimo || true

            # 사용하지 않는 이미지, 컨테이너, 볼륨 정리
            docker image prune -f
            docker container prune -f
            docker volume prune -f

            docker images | grep motimo
            docker ps -a | grep motimo

            # 새 이미지 풀링
            docker pull ${{ secrets.DOCKER_USERNAME }}/motimo:${{ needs.build.outputs.commit_hash }}

            # 새 컨테이너 실행
            docker run -d --env-file .env \
              -e SPRING_PROFILES_ACTIVE=dv \
              -e JAVA_OPTS="-Xms256m -Xmx512m -XX:+UseG1GC -XX:+PrintGCDetails -XX:+PrintGCDateStamps -Xloggc:/logs/gc.log" \
              --name motimo \
              -p 8080:8080 \
              ${{ secrets.DOCKER_USERNAME }}/motimo:${{ needs.build.outputs.commit_hash }}

          EOF
