name: Motimo CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build bootJar
      run: ./gradlew :motimo-api:bootJar -x test

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: motimo-jar
        path: motimo-api/build/libs/motimo-api-*.jar
