name: Motimo CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Extract Git short SHA
        id: git_info
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Build JAR
        run: ./gradlew :motimo-api:bootJar -x test

      - name: Prepare JAR for Docker
        run: |
          mkdir -p ./docker-build
          cp motimo-api/build/libs/motimo-api-*.jar ./docker-build/app.jar

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Copy docker-compose file to server
        run: |
          scp docker-compose.dv.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/opc/motimo/

      - name: Build and push Docker image
        run: |
          docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/motimo:${{ steps.git_info.outputs.commit_hash }} ./docker-build
          docker tag ${{ secrets.DOCKER_USERNAME }}/motimo:${{ steps.git_info.outputs.commit_hash }} ${{ secrets.DOCKER_USERNAME }}/motimo:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/motimo:${{ steps.git_info.outputs.commit_hash }}
          docker push ${{ secrets.DOCKER_USERNAME }}/motimo:latest
