name: Motimo CD

on:
  workflow_run:
    workflows: ["Motimo CI"] 
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << EOF
            set -x

            docker ps -a --filter "ancestor=${{ secrets.DOCKER_USERNAME }}/motimo" --format "{{.ID}}" | xargs -r docker rm -f
            docker stop motimo || true
            docker rm motimo || true

            docker image prune -f
            docker container prune -f
            docker volume prune -f

            docker pull ${{ secrets.DOCKER_USERNAME }}/motimo:latest

            docker run -d --env-file .env \
              -e SPRING_PROFILES_ACTIVE=dv \
              -e JAVA_OPTS="-Xms256m -Xmx512m -XX:+UseG1GC -XX:+PrintGCDetails -XX:+PrintGCDateStamps -Xloggc:/logs/gc.log" \
              --name motimo \
              -p 8080:8080 \
              ${{ secrets.DOCKER_USERNAME }}/motimo:latest
          EOF
